// <auto-generated />
using System;
using GenericHostApp.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;

namespace GenericHostApp.Migrations
{
    [DbContext(typeof(BasketContext))]
    partial class BasketContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview1-28290");

            modelBuilder.Entity("GenericHostApp.Model.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CustomerId");

                    b.HasKey("Id");

                    b.ToTable("Baskets");

                    b.SeedData(new[]
                    {
                        new { Id = 1, CustomerId = 1 }
                    });
                });

            modelBuilder.Entity("GenericHostApp.Model.BasketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BasketId");

                    b.Property<decimal>("Cost");

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.ToTable("BasketItems");

                    b.SeedData(new[]
                    {
                        new { Id = 1, BasketId = 1, Cost = 5m, Description = "Something that originally cost $5." }
                    });
                });

            modelBuilder.Entity("GenericHostApp.Model.BasketItem", b =>
                {
                    b.HasOne("GenericHostApp.Model.Basket")
                        .WithMany("Items")
                        .HasForeignKey("BasketId");
                });
#pragma warning restore 612, 618
        }
    }
}
